# Connect Intensive - Machine Learning Nanodegree
# Lesson 2: Datasets and Questions- Enron Dataset Mini-Project

## Objectives
  - Work through the Datasets and Questions lesson from [ud-120](https://www.udacity.com/course/intro-to-machine-learning--ud120) within the Jupyter Notebook environment
  - Introduce [the `pickle` module](https://docs.python.org/2/library/pickle.html) from the Python Standard Library for preserving data structures in Python
  - Practice loading data from different directories
  - Review stacking and unstacking in `pandas` to [reshape a `DataFrame`](http://pandas.pydata.org/pandas-docs/stable/reshaping.html)
  - Explore and understand data sets, particularly those with many missing values
  
## Prerequisites
  - You should be familiar with `pandas` (lesson 1 in the [UConnect-Intensive repo](https://github.com/ryanjferrin/UConnect-Intensive))

## Background

The Enron fraud is a big, messy and totally fascinating story about corporate malfeasance of nearly every imaginable type. The Enron email and financial datasets are also big, messy treasure troves of information, which become much more useful once you know your way around them a bit. The Udacity team has combined the email and finance data into a single dataset, which you’ll explore in this mini-project.
 
 
In the online course [Katie Malone](http://blog.udacity.com/2016/04/women-in-machine-learning-katie-malone.html) discusses the Enron scandal, introduces the Enron email corpus and defines and identifies a person-of-interest (POI). 

**POI**: Indicted, settled without admitting guilt, testified in exchange for immunity.

**Goal**: Use machine learning to answer the question:  

**"Can we identify patterns in the emails of people who were POIs?"**

## Getting Started
The Datasets and Questions lesson in the Data Modeling section is based on Enron finance and email data. These datasets are located in the [**ud120-projects** repo](https://github.com/udacity/ud120-projects) on GitHub. Please clone the **ud120-projects** repo to your local machine.

## Pickle
 [The `pickle` module](https://docs.python.org/2/library/pickle.html) is a fast, efficient way to preserve (or pickle) data structures (*e.g.* dictionaries, lists, tuples, sets...), without having to structure or organize your output file. `Pickle` will know exactly how to serialize (or write) those structures to file. You can un-pickle the data structures using `pickle.load()`. 


More details regarding `pickle` can be found here-[this reference on Serializing Python Objects](http://www.diveintopython3.net/serializing.html) from Dive Into Python 3.

**Run** the cell below to import the `pickle` module. (**shift + enter** or **shift + return**)

In [114]:
try:
    import pickle
    print("Successfully imported pickle!")
except ImportError:
    print("Could not import pickle")

Successfully imported pickle!

## Update working directory 

The [Magic Function](http://ipython.readthedocs.io/en/stable/interactive/tutorial.html#magics-explained) `%cd "..."` changes the working directory in the Jupyter Notebook.

**Update** the Magic Function `%cd "..."` in the cell below to indicate the correct path of the **ud120-projects** directory on your local machine.

Then **run** the cell below to load the Enron data!

In [115]:
# Ensure that you write the full path, up to and including "ud120-projects"
%cd "../../../datasets/ud120-projects"

try:
    enron_data = pickle.load(open("final_project/final_project_dataset.pkl", "r")) # May require "rb" instead of "r"
    print("Enron dataset loaded succesfully!")
except IOError:
    print("Enron dataset not loaded")

[Errno 2] No such file or directory: '../../../datasets/ud120-projects'
/Users/harrisleow/Desktop/Udacity_Connect_intensive/datasets/ud120-projects
Enron dataset loaded succesfully!

## Transforming data from Dictionary to DataFrame
The variable `enron_data` is a dictionary object. Dictionaries are not displayed as nicely as `pandas` `DataFrame` objects within the Jupyter Notebook environment. Let's convert `enron_data` to a `DataFrame` object. 

Use either [the method `pandas.DataFrame.from_dict()`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.from_dict.html) or simply use [the constructor `pandas.DataFrame()`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html) either works. 

**Run** the cell below to:
  - import `pandas` and `display`.
  - set some display options.
  - create a `DataFrame` object for the Enron data.
  - display the Enron data.

In [116]:
try:
    import pandas as pd
    print("Successfully imported pandas! (Version {})".format(pd.__version__))
    pd.options.display.max_rows = 100
except ImportError:
    print("Could not import pandas!")

try:
    from IPython.display import display
    print("Successfully imported display from IPython.display!")
except ImportError:
    print("Could not import display from IPython.display")
    
enron_df = pd.DataFrame.from_dict(enron_data)
display(enron_df)
print enron_df

Successfully imported pandas! (Version 0.19.2)
Successfully imported display from IPython.display!

,ALLEN PHILLIP K,BADUM JAMES P,BANNANTINE JAMES M,BAXTER JOHN C,BAY FRANKLIN R,BAZELIDES PHILIP J,BECK SALLY W,BELDEN TIMOTHY N,BELFER ROBERT,BERBERIAN DAVID,...,WASAFF GEORGE,WESTFAHL RICHARD K,WHALEY DAVID A,WHALLEY LAWRENCE G,WHITE JR THOMAS E,WINOKUR JR. HERBERT S,WODRASKA JOHN,WROBEL BRUCE,YEAGER F SCOTT,YEAP SOON
bonus,4175000,NaN,NaN,1200000,400000,NaN,700000,5249999,NaN,NaN,...,325000,NaN,NaN,3000000,450000,NaN,NaN,NaN,NaN,NaN
deferral_payments,2869717,178980,NaN,1295738,260455,684694,NaN,2144013,-102500,NaN,...,831299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
deferred_income,-3081055,NaN,-5104,-1386055,-201641,NaN,NaN,-2334434,NaN,NaN,...,-583325,-10800,NaN,NaN,NaN,-25000,NaN,NaN,NaN,NaN
director_fees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3285,NaN,...,NaN,NaN,NaN,NaN,NaN,108579,NaN,NaN,NaN,NaN
email_address,phillip.allen@enron.com,NaN,james.bannantine@enron.com,NaN,frank.bay@enron.com,NaN,sally.beck@enron.com,tim.belden@enron.com,NaN,david.berberian@enron.com,...,george.wasaff@enron.com,dick.westfahl@enron.com,NaN,greg.whalley@enron.com,thomas.white@enron.com,NaN,john.wodraska@enron.com,NaN,scott.yeager@enron.com,NaN
exercised_stock_options,1729541,257817,4046157,6680544,NaN,1599641,NaN,953136,3285,1624396,...,1668260,NaN,98718,3282960,1297049,NaN,NaN,139130,8308552,192758
expenses,13868,3486,56301,11200,129142,NaN,37172,17355,NaN,11892,...,NaN,51870,NaN,57838,81353,1413,NaN,NaN,53947,55097
from_messages,2195,NaN,29,NaN,NaN,NaN,4343,484,NaN,NaN,...,30,NaN,NaN,556,NaN,NaN,NaN,NaN,NaN,NaN
from_poi_to_this_person,47,NaN,39,NaN,NaN,NaN,144,228,NaN,NaN,...,22,NaN,NaN,186,NaN,NaN,NaN,NaN,NaN,NaN
from_this_person_to_poi,65,NaN,0,NaN,NaN,NaN,386,108,NaN,NaN,...,7,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN
loan_advances,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
long_term_incentive,304805,NaN,NaN,1586055,NaN,93750,NaN,NaN,NaN,NaN,...,200000,256191,NaN,808346,NaN,NaN,NaN,NaN,NaN,NaN
other,152,NaN,864523,2660303,69,874,566,210698,NaN,NaN,...,1425,401130,NaN,301026,1085463,NaN,189583,NaN,147950,NaN
poi,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
restricted_stock,126027,NaN,1757552,3942714,145796,NaN,126027,157569,NaN,869220,...,388167,384930,NaN,2796177,13847074,NaN,NaN,NaN,3576206,NaN
restricted_stock_deferred,-126027,NaN,-560222,NaN,-82782,NaN,NaN,NaN,44093,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary,201955,NaN,477,267102,239671,80818,231330,213999,NaN,216582,...,259996,63744,NaN,510364,317543,NaN,NaN,NaN,158403,NaN
shared_receipt_with_poi,1407,NaN,465,NaN,NaN,NaN,2639,5521,NaN,NaN,...,337,NaN,NaN,3920,NaN,NaN,NaN,NaN,NaN,NaN
to_messages,2902,NaN,566,NaN,NaN,NaN,7315,7991,NaN,NaN,...,400,NaN,NaN,6019,NaN,NaN,NaN,NaN,NaN,NaN
total_payments,4484442,182466,916197,5634343,827696,860136,969068,5501630,102500,228474,...,1034395,762135,NaN,4677574,1934359,84992,189583,NaN,360300,55097
total_stock_value,1729541,257817,5243487,10623258,63014,1599641,126027,1110705,-44093,2493616,...,2056427,384930,98718,6079137,15144123,NaN,NaN,139130,11884758,192758

                                   ALLEN PHILLIP K BADUM JAMES P  \
bonus                                      4175000           NaN
deferral_payments                          2869717        178980
deferred_income                           -3081055           NaN
director_fees                                  NaN           NaN
email_address              phillip.allen@enron.com           NaN
exercised_stock_options                    1729541        257817
expenses                                     13868          3486
from_messages                                 2195           NaN
from_poi_to_this_person                         47           NaN
from_this_person_to_poi                         65           NaN
loan_advances                                  NaN           NaN
long_term_incentive                         304805           NaN
other                                          152           NaN
poi                                          False         False
restricted_stock                            126027           NaN
restricted_stock_deferred                  -126027           NaN
salary                                      201955           NaN
shared_receipt_with_poi                       1407           NaN
to_messages                                   2902           NaN
total_payments                             4484442        182466
total_stock_value                          1729541        257817

                                   BANNANTINE JAMES M BAXTER JOHN C  \
bonus                                             NaN       1200000
deferral_payments                                 NaN       1295738
deferred_income                                 -5104      -1386055
director_fees                                     NaN           NaN
email_address              james.bannantine@enron.com           NaN
exercised_stock_options                       4046157       6680544
expenses                                        56301         11200
from_messages                                      29           NaN
from_poi_to_this_person                            39           NaN
from_this_person_to_poi                             0           NaN
loan_advances                                     NaN           NaN
long_term_incentive                               NaN       1586055
other                                          864523       2660303
poi                                             False         False
restricted_stock                              1757552       3942714
restricted_stock_deferred                     -560222           NaN
salary                                            477        267102
shared_receipt_with_poi                           465           NaN
to_messages                                       566           NaN
total_payments                                 916197       5634343
total_stock_value                             5243487      10623258

                                BAY FRANKLIN R BAZELIDES PHILIP J  \
bonus                                   400000                NaN
deferral_payments                       260455             684694
deferred_income                        -201641                NaN
director_fees                              NaN                NaN
email_address              frank.bay@enron.com                NaN
exercised_stock_options                    NaN            1599641
expenses                                129142                NaN
from_messages                              NaN                NaN
from_poi_to_this_person                    NaN                NaN
from_this_person_to_poi                    NaN                NaN
loan_advances                              NaN                NaN
long_term_incentive                        NaN              93750
other                                       69                874
poi                                      False              False
restricted_stock                        145796                NaN
restricted_stock_deferred               -82782                NaN
salary                                  239671              80818
shared_receipt_with_poi                    NaN                NaN
to_messages                                NaN                NaN
total_payments                          827696             860136
total_stock_value                        63014            1599641

                                   BECK SALLY W      BELDEN TIMOTHY N  \
bonus                                    700000               5249999
deferral_payments                           NaN               2144013
deferred_income                             NaN              -2334434
director_fees                               NaN                   NaN
email_address              sally.beck@enron.com  tim.belden@enron.com
exercised_stock_options                     NaN                953136
expenses                                  37172                 17355
from_messages                              4343                   484
from_poi_to_this_person                     144                   228
from_this_person_to_poi                     386                   108
loan_advances                               NaN                   NaN
long_term_incentive                         NaN                   NaN
other                                       566                210698
poi                                       False                  True
restricted_stock                         126027                157569
restricted_stock_deferred                   NaN                   NaN
salary                                   231330                213999
shared_receipt_with_poi                    2639                  5521
to_messages                                7315                  7991
total_payments                           969068               5501630
total_stock_value                        126027               1110705

                          BELFER ROBERT            BERBERIAN DAVID    ...     \
bonus                               NaN                        NaN    ...
deferral_payments               -102500                        NaN    ...
deferred_income                     NaN                        NaN    ...
director_fees                      3285                        NaN    ...
email_address                       NaN  david.berberian@enron.com    ...
exercised_stock_options            3285                    1624396    ...
expenses                            NaN                      11892    ...
from_messages                       NaN                        NaN    ...
from_poi_to_this_person             NaN                        NaN    ...
from_this_person_to_poi             NaN                        NaN    ...
loan_advances                       NaN                        NaN    ...
long_term_incentive                 NaN                        NaN    ...
other                               NaN                        NaN    ...
poi                               False                      False    ...
restricted_stock                    NaN                     869220    ...
restricted_stock_deferred         44093                        NaN    ...
salary                              NaN                     216582    ...
shared_receipt_with_poi             NaN                        NaN    ...
to_messages                         NaN                        NaN    ...
total_payments                   102500                     228474    ...
total_stock_value                -44093                    2493616    ...

                                     WASAFF GEORGE       WESTFAHL RICHARD K  \
bonus                                       325000                      NaN
deferral_payments                           831299                      NaN
deferred_income                            -583325                   -10800
director_fees                                  NaN                      NaN
email_address              george.wasaff@enron.com  dick.westfahl@enron.com
exercised_stock_options                    1668260                      NaN
expenses                                       NaN                    51870
from_messages                                   30                      NaN
from_poi_to_this_person                         22                      NaN
from_this_person_to_poi                          7                      NaN
loan_advances                                  NaN                      NaN
long_term_incentive                         200000                   256191
other                                         1425                   401130
poi                                          False                    False
restricted_stock                            388167                   384930
restricted_stock_deferred                      NaN                      NaN
salary                                      259996                    63744
shared_receipt_with_poi                        337                      NaN
to_messages                                    400                      NaN
total_payments                             1034395                   762135
total_stock_value                          2056427                   384930

                          WHALEY DAVID A      WHALLEY LAWRENCE G  \
bonus                                NaN                 3000000
deferral_payments                    NaN                     NaN
deferred_income                      NaN                     NaN
director_fees                        NaN                     NaN
email_address                        NaN  greg.whalley@enron.com
exercised_stock_options            98718                 3282960
expenses                             NaN                   57838
from_messages                        NaN                     556
from_poi_to_this_person              NaN                     186
from_this_person_to_poi              NaN                      24
loan_advances                        NaN                     NaN
long_term_incentive                  NaN                  808346
other                                NaN                  301026
poi                                False                   False
restricted_stock                     NaN                 2796177
restricted_stock_deferred            NaN                     NaN
salary                               NaN                  510364
shared_receipt_with_poi              NaN                    3920
to_messages                          NaN                    6019
total_payments                       NaN                 4677574
total_stock_value                  98718                 6079137

                                WHITE JR THOMAS E WINOKUR JR. HERBERT S  \
bonus                                      450000                   NaN
deferral_payments                             NaN                   NaN
deferred_income                               NaN                -25000
director_fees                                 NaN                108579
email_address              thomas.white@enron.com                   NaN
exercised_stock_options                   1297049                   NaN
expenses                                    81353                  1413
from_messages                                 NaN                   NaN
from_poi_to_this_person                       NaN                   NaN
from_this_person_to_poi                       NaN                   NaN
loan_advances                                 NaN                   NaN
long_term_incentive                           NaN                   NaN
other                                     1085463                   NaN
poi                                         False                 False
restricted_stock                         13847074                   NaN
restricted_stock_deferred                     NaN                   NaN
salary                                     317543                   NaN
shared_receipt_with_poi                       NaN                   NaN
to_messages                                   NaN                   NaN
total_payments                            1934359                 84992
total_stock_value                        15144123                   NaN

                                     WODRASKA JOHN WROBEL BRUCE  \
bonus                                          NaN          NaN
deferral_payments                              NaN          NaN
deferred_income                                NaN          NaN
director_fees                                  NaN          NaN
email_address              john.wodraska@enron.com          NaN
exercised_stock_options                        NaN       139130
expenses                                       NaN          NaN
from_messages                                  NaN          NaN
from_poi_to_this_person                        NaN          NaN
from_this_person_to_poi                        NaN          NaN
loan_advances                                  NaN          NaN
long_term_incentive                            NaN          NaN
other                                       189583          NaN
poi                                          False        False
restricted_stock                               NaN          NaN
restricted_stock_deferred                      NaN          NaN
salary                                         NaN          NaN
shared_receipt_with_poi                        NaN          NaN
to_messages                                    NaN          NaN
total_payments                              189583          NaN
total_stock_value                              NaN       139130

                                   YEAGER F SCOTT YEAP SOON
bonus                                         NaN       NaN
deferral_payments                             NaN       NaN
deferred_income                               NaN       NaN
director_fees                                 NaN       NaN
email_address              scott.yeager@enron.com       NaN
exercised_stock_options                   8308552    192758
expenses                                    53947     55097
from_messages                                 NaN       NaN
from_poi_to_this_person                       NaN       NaN
from_this_person_to_poi                       NaN       NaN
loan_advances                                 NaN       NaN
long_term_incentive                           NaN       NaN
other                                      147950       NaN
poi                                          True     False
restricted_stock                          3576206       NaN
restricted_stock_deferred                     NaN       NaN
salary                                     158403       NaN
shared_receipt_with_poi                       NaN       NaN
to_messages                                   NaN       NaN
total_payments                             360300     55097
total_stock_value                        11884758    192758

[21 rows x 146 columns]

## Stacking, unstacking, and rearranging

The data is not formatted in the proper manner. The variables (features) should be in the columns and the unique instances should be in the rows. 

The following functions can be used to resolve this issue. 

- [`pandas.DataFrame.stack()`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.stack.html) 
- [`pandas.DataFrame.unstack()`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.unstack.html)

First, we need to `stack` the current column indices, moving them to the innermost level of the row index.

**Run** the cell below to see the results of calling `enron_df.stack()`

In [117]:
enron_df.stack()

bonus              ALLEN PHILLIP K                    4175000
                   BADUM JAMES P                          NaN
                   BANNANTINE JAMES M                     NaN
                   BAXTER JOHN C                      1200000
                   BAY FRANKLIN R                      400000
                   BAZELIDES PHILIP J                     NaN
                   BECK SALLY W                        700000
                   BELDEN TIMOTHY N                   5249999
                   BELFER ROBERT                          NaN
                   BERBERIAN DAVID                        NaN
                   BERGSIEKER RICHARD P                250000
                   BHATNAGAR SANJAY                       NaN
                   BIBI PHILIPPE A                    1000000
                   BLACHMAN JEREMY M                   850000
                   BLAKE JR. NORMAN P                     NaN
                   BOWEN JR RAYMOND M                 1350000
                   BROWN MICHAEL                          NaN
                   BUCHANAN HAROLD G                   500000
                   BUTTS ROBERT H                      750000
                   BUY RICHARD B                       900000
                   CALGER CHRISTOPHER F               1250000
                   CARTER REBECCA C                    300000
                   CAUSEY RICHARD A                   1000000
                   CHAN RONNIE                            NaN
                   CHRISTODOULOU DIOMEDES                 NaN
                   CLINE KENNETH W                        NaN
                   COLWELL WESLEY                     1200000
                   CORDES WILLIAM R                       NaN
                   COX DAVID                           800000
                   CUMBERLAND MICHAEL S                325000
                   DEFFNER JOSEPH M                    600000
                   DELAINEY DAVID W                   3000000
                   DERRICK JR. JAMES V                 800000
                   DETMERING TIMOTHY J                 425000
                   DIETRICH JANET R                    600000
                   DIMICHELE RICHARD G                1000000
                   DODSON KEITH                         70000
                   DONAHUE JR JEFFREY M                800000
                   DUNCAN JOHN H                          NaN
                   DURAN WILLIAM D                     750000
                   ECHOLS JOHN B                       200000
                   ELLIOTT STEVEN                      350000
                   FALLON JAMES B                     2500000
                   FASTOW ANDREW S                    1300000
                   FITZGERALD JAY L                    350000
                   FOWLER PEGGY                           NaN
                   FOY JOE                                NaN
                   FREVERT MARK A                     2000000
                   FUGH JOHN L                            NaN
                   GAHN ROBERT S                       509870
                                                      ...
total_stock_value  MORAN MICHAEL P                     221141
                   MORDAUNT KRISTINA M                 208510
                   MULLER MARK S                      1416848
                   MURRAY JULIA H                      597461
                   NOLES JAMES L                       368705
                   OLSON CINDY K                      2606763
                   OVERDYKE JR JERE C                 7307594
                   PAI LOU L                         23817930
                   PEREIRA PAULO V. FERRAZ                NaN
                   PICKERING MARK R                     28798
                   PIPER GREGORY F                     880290
                   PIRO JIM                             47304
                   POWERS WILLIAM                         NaN
                   PRENTICE JAMES                     1095040
                   REDMOND BRIAN L                    7890324
                   REYNOLDS LAWRENCE                  4221891
                   RICE KENNETH D                    22542539
                   RIEKER PAULA H                     1918887
                   SAVAGE FRANK                           NaN
                   SCRIMSHAW MATTHEW                   759557
                   SHANKMAN JEFFREY A                 2072035
                   SHAPIRO RICHARD S                   987001
                   SHARP VICTORIA T                    494136
                   SHELBY REX                         2493616
                   SHERRICK JEFFREY B                 1832468
                   SHERRIFF JOHN R                    3128982
                   SKILLING JEFFREY K                26093672
                   STABLER FRANK                       511734
                   SULLIVAN-SHAKLOVITZ COLLEEN        1362375
                   SUNDE MARTIN                        698920
                   TAYLOR MITCHELL S                  3745048
                   THE TRAVEL AGENCY IN THE PARK          NaN
                   THORN TERENCE H                    4817796
                   TILNEY ELIZABETH A                 1168042
                   TOTAL                            434509511
                   UMANOFF ADAM S                         NaN
                   URQUHART JOHN A                        NaN
                   WAKEHAM JOHN                           NaN
                   WALLS JR ROBERT H                  5898997
                   WALTERS GARETH W                   1030329
                   WASAFF GEORGE                      2056427
                   WESTFAHL RICHARD K                  384930
                   WHALEY DAVID A                       98718
                   WHALLEY LAWRENCE G                 6079137
                   WHITE JR THOMAS E                 15144123
                   WINOKUR JR. HERBERT S                  NaN
                   WODRASKA JOHN                          NaN
                   WROBEL BRUCE                        139130
                   YEAGER F SCOTT                    11884758
                   YEAP SOON                           192758
dtype: object

We see that the result of `enron_df.stack()` is a `Series` object, where the innermost (rightmost) level of the index is the person's name in the Enron data set, while the outermost (leftmost) level of the index is the feature. If we call `unstack()` on the resulting `series` without specifying a level, we'll just revert to the original `DataFrame`.

**Run** the cell below to see the result of calling `enron_df.stack().unstack()`

In [118]:
enron_df.stack().unstack()

,ALLEN PHILLIP K,BADUM JAMES P,BANNANTINE JAMES M,BAXTER JOHN C,BAY FRANKLIN R,BAZELIDES PHILIP J,BECK SALLY W,BELDEN TIMOTHY N,BELFER ROBERT,BERBERIAN DAVID,...,WASAFF GEORGE,WESTFAHL RICHARD K,WHALEY DAVID A,WHALLEY LAWRENCE G,WHITE JR THOMAS E,WINOKUR JR. HERBERT S,WODRASKA JOHN,WROBEL BRUCE,YEAGER F SCOTT,YEAP SOON
bonus,4175000,NaN,NaN,1200000,400000,NaN,700000,5249999,NaN,NaN,...,325000,NaN,NaN,3000000,450000,NaN,NaN,NaN,NaN,NaN
deferral_payments,2869717,178980,NaN,1295738,260455,684694,NaN,2144013,-102500,NaN,...,831299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
deferred_income,-3081055,NaN,-5104,-1386055,-201641,NaN,NaN,-2334434,NaN,NaN,...,-583325,-10800,NaN,NaN,NaN,-25000,NaN,NaN,NaN,NaN
director_fees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3285,NaN,...,NaN,NaN,NaN,NaN,NaN,108579,NaN,NaN,NaN,NaN
email_address,phillip.allen@enron.com,NaN,james.bannantine@enron.com,NaN,frank.bay@enron.com,NaN,sally.beck@enron.com,tim.belden@enron.com,NaN,david.berberian@enron.com,...,george.wasaff@enron.com,dick.westfahl@enron.com,NaN,greg.whalley@enron.com,thomas.white@enron.com,NaN,john.wodraska@enron.com,NaN,scott.yeager@enron.com,NaN
exercised_stock_options,1729541,257817,4046157,6680544,NaN,1599641,NaN,953136,3285,1624396,...,1668260,NaN,98718,3282960,1297049,NaN,NaN,139130,8308552,192758
expenses,13868,3486,56301,11200,129142,NaN,37172,17355,NaN,11892,...,NaN,51870,NaN,57838,81353,1413,NaN,NaN,53947,55097
from_messages,2195,NaN,29,NaN,NaN,NaN,4343,484,NaN,NaN,...,30,NaN,NaN,556,NaN,NaN,NaN,NaN,NaN,NaN
from_poi_to_this_person,47,NaN,39,NaN,NaN,NaN,144,228,NaN,NaN,...,22,NaN,NaN,186,NaN,NaN,NaN,NaN,NaN,NaN
from_this_person_to_poi,65,NaN,0,NaN,NaN,NaN,386,108,NaN,NaN,...,7,NaN,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN
loan_advances,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
long_term_incentive,304805,NaN,NaN,1586055,NaN,93750,NaN,NaN,NaN,NaN,...,200000,256191,NaN,808346,NaN,NaN,NaN,NaN,NaN,NaN
other,152,NaN,864523,2660303,69,874,566,210698,NaN,NaN,...,1425,401130,NaN,301026,1085463,NaN,189583,NaN,147950,NaN
poi,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,True,False
restricted_stock,126027,NaN,1757552,3942714,145796,NaN,126027,157569,NaN,869220,...,388167,384930,NaN,2796177,13847074,NaN,NaN,NaN,3576206,NaN
restricted_stock_deferred,-126027,NaN,-560222,NaN,-82782,NaN,NaN,NaN,44093,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary,201955,NaN,477,267102,239671,80818,231330,213999,NaN,216582,...,259996,63744,NaN,510364,317543,NaN,NaN,NaN,158403,NaN
shared_receipt_with_poi,1407,NaN,465,NaN,NaN,NaN,2639,5521,NaN,NaN,...,337,NaN,NaN,3920,NaN,NaN,NaN,NaN,NaN,NaN
to_messages,2902,NaN,566,NaN,NaN,NaN,7315,7991,NaN,NaN,...,400,NaN,NaN,6019,NaN,NaN,NaN,NaN,NaN,NaN
total_payments,4484442,182466,916197,5634343,827696,860136,969068,5501630,102500,228474,...,1034395,762135,NaN,4677574,1934359,84992,189583,NaN,360300,55097
total_stock_value,1729541,257817,5243487,10623258,63014,1599641,126027,1110705,-44093,2493616,...,2056427,384930,98718,6079137,15144123,NaN,NaN,139130,11884758,192758

We need to `unstack` the *outermost* level of the index, but by default, the function will `unstack` the *innermost* level of the index.

**Run** the cell below *once* to correctly `stack` and `unstack` the Enron `DataFrame` to move the instances (names) to rows and features (variables) to columns.

In [119]:
enron_df = enron_df.stack().unstack(0)
display(enron_df)

,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,...,long_term_incentive,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
ALLEN PHILLIP K,4175000,2869717,-3081055,NaN,phillip.allen@enron.com,1729541,13868,2195,47,65,...,304805,152,False,126027,-126027,201955,1407,2902,4484442,1729541
BADUM JAMES P,NaN,178980,NaN,NaN,NaN,257817,3486,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,182466,257817
BANNANTINE JAMES M,NaN,NaN,-5104,NaN,james.bannantine@enron.com,4046157,56301,29,39,0,...,NaN,864523,False,1757552,-560222,477,465,566,916197,5243487
BAXTER JOHN C,1200000,1295738,-1386055,NaN,NaN,6680544,11200,NaN,NaN,NaN,...,1586055,2660303,False,3942714,NaN,267102,NaN,NaN,5634343,10623258
BAY FRANKLIN R,400000,260455,-201641,NaN,frank.bay@enron.com,NaN,129142,NaN,NaN,NaN,...,NaN,69,False,145796,-82782,239671,NaN,NaN,827696,63014
BAZELIDES PHILIP J,NaN,684694,NaN,NaN,NaN,1599641,NaN,NaN,NaN,NaN,...,93750,874,False,NaN,NaN,80818,NaN,NaN,860136,1599641
BECK SALLY W,700000,NaN,NaN,NaN,sally.beck@enron.com,NaN,37172,4343,144,386,...,NaN,566,False,126027,NaN,231330,2639,7315,969068,126027
BELDEN TIMOTHY N,5249999,2144013,-2334434,NaN,tim.belden@enron.com,953136,17355,484,228,108,...,NaN,210698,True,157569,NaN,213999,5521,7991,5501630,1110705
BELFER ROBERT,NaN,-102500,NaN,3285,NaN,3285,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,44093,NaN,NaN,NaN,102500,-44093
BERBERIAN DAVID,NaN,NaN,NaN,NaN,david.berberian@enron.com,1624396,11892,NaN,NaN,NaN,...,NaN,NaN,False,869220,NaN,216582,NaN,NaN,228474,2493616
BERGSIEKER RICHARD P,250000,NaN,-485813,NaN,rick.bergsieker@enron.com,NaN,59175,59,4,0,...,180250,427316,False,659249,NaN,187922,233,383,618850,659249
BHATNAGAR SANJAY,NaN,NaN,NaN,137864,sanjay.bhatnagar@enron.com,2604490,NaN,29,0,1,...,NaN,137864,False,-2604490,15456290,NaN,463,523,15456290,NaN
BIBI PHILIPPE A,1000000,NaN,NaN,NaN,philippe.bibi@enron.com,1465734,38559,40,23,8,...,369721,425688,False,378082,NaN,213625,1336,1607,2047593,1843816
BLACHMAN JEREMY M,850000,NaN,NaN,NaN,jeremy.blachman@enron.com,765313,84208,14,25,2,...,831809,272,False,189041,NaN,248546,2326,2475,2014835,954354
BLAKE JR. NORMAN P,NaN,NaN,-113784,113784,NaN,NaN,1279,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,1279,NaN
BOWEN JR RAYMOND M,1350000,NaN,-833,NaN,raymond.bowen@enron.com,NaN,65907,27,140,15,...,974293,1621,True,252055,NaN,278601,1593,1858,2669589,252055
BROWN MICHAEL,NaN,NaN,NaN,NaN,michael.brown@enron.com,NaN,49288,41,13,1,...,NaN,NaN,False,NaN,NaN,NaN,761,1486,49288,NaN
BUCHANAN HAROLD G,500000,NaN,NaN,NaN,john.buchanan@enron.com,825464,600,125,0,0,...,304805,1215,False,189041,NaN,248017,23,1088,1054637,1014505
BUTTS ROBERT H,750000,NaN,-75000,NaN,bob.butts@enron.com,NaN,9410,NaN,NaN,NaN,...,175000,150656,False,417619,NaN,261516,NaN,NaN,1271582,417619
BUY RICHARD B,900000,649584,-694862,NaN,rick.buy@enron.com,2542813,NaN,1053,156,71,...,769862,400572,False,901657,NaN,330546,2333,3523,2355702,3444470
CALGER CHRISTOPHER F,1250000,NaN,-262500,NaN,christopher.calger@enron.com,NaN,35818,144,199,25,...,375304,486,True,126027,NaN,240189,2188,2598,1639297,126027
CARTER REBECCA C,300000,NaN,-159792,NaN,rebecca.carter@enron.com,NaN,NaN,15,29,7,...,75000,540,False,307301,-307301,261809,196,312,477557,NaN
CAUSEY RICHARD A,1000000,NaN,-235000,NaN,richard.causey@enron.com,NaN,30674,49,58,12,...,350000,307895,True,2502063,NaN,415189,1585,1892,1868758,2502063
CHAN RONNIE,NaN,NaN,-98784,98784,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,32460,-32460,NaN,NaN,NaN,NaN,NaN
CHRISTODOULOU DIOMEDES,NaN,NaN,NaN,NaN,diomedes.christodoulou@enron.com,5127155,NaN,NaN,NaN,NaN,...,NaN,NaN,False,950730,NaN,NaN,NaN,NaN,NaN,6077885
CLINE KENNETH W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,662086,-472568,NaN,NaN,NaN,NaN,189518
COLWELL WESLEY,1200000,27610,-144062,NaN,wes.colwell@enron.com,NaN,16514,40,240,11,...,NaN,101740,True,698242,NaN,288542,1132,1758,1490344,698242
CORDES WILLIAM R,NaN,NaN,NaN,NaN,bill.cordes@enron.com,651850,NaN,12,10,0,...,NaN,NaN,False,386335,NaN,NaN,58,764,NaN,1038185
COX DAVID,800000,NaN,-41250,NaN,chip.cox@enron.com,117551,27861,33,0,4,...,NaN,494,False,378082,NaN,314288,71,102,1101393,495633
CUMBERLAND MICHAEL S,325000,NaN,NaN,NaN,NaN,NaN,22344,NaN,NaN,NaN,...,275000,713,False,207940,NaN,184899,NaN,NaN,807956,207940
DEFFNER JOSEPH M,600000,NaN,NaN,NaN,joseph.deffner@enron.com,17378,41626,74,115,4,...,335349,25553,False,141833,NaN,206121,552,714,1208649,159211
DELAINEY DAVID W,3000000,NaN,NaN,NaN,david.delainey@enron.com,2291113,86174,3069,66,609,...,1294981,1661,True,1323148,NaN,365163,2097,3093,4747979,3614261
DERRICK JR. JAMES V,800000,NaN,-1284000,NaN,james.derrick@enron.com,8831913,51124,909,64,20,...,484000,7482,False,1787380,-1787380,492375,1401,2181,550981,8831913
DETMERING TIMOTHY J,425000,875307,-775241,NaN,timothy.detmering@enron.com,2027865,52255,NaN,NaN,NaN,...,415657,1105,False,315068,-315068,210500,NaN,NaN,1204583,2027865
DIETRICH JANET R,600000,NaN,NaN,NaN,janet.dietrich@enron.com,1550019,3475,63,305,14,...,556416,473,False,315068,NaN,250100,1902,2572,1410464,1865087
DIMICHELE RICHARD G,1000000,NaN,NaN,NaN,richard.dimichele@enron.com,8191755,35812,NaN,NaN,NaN,...,694862,374689,False,126027,NaN,262788,NaN,NaN,2368151,8317782
DODSON KEITH,70000,NaN,NaN,NaN,keith.dodson@enron.com,NaN,28164,14,10,3,...,NaN,774,False,NaN,NaN,221003,114,176,319941,NaN
DONAHUE JR JEFFREY M,800000,NaN,-300000,NaN,jeff.donahue@enron.com,765920,96268,22,188,11,...,NaN,891,False,315068,NaN,278601,772,865,875760,1080988
DUNCAN JOHN H,NaN,NaN,-25000,102492,NaN,371750,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,77492,371750
DURAN WILLIAM D,750000,NaN,NaN,NaN,w.duran@enron.com,1451869,25785,12,106,3,...,1105218,1568,False,189041,NaN,210692,599,904,2093263,1640910
ECHOLS JOHN B,200000,NaN,NaN,NaN,john.echols@enron.com,601438,21530,NaN,NaN,NaN,...,2234774,53775,False,407503,NaN,182245,NaN,NaN,2692324,1008941
ELLIOTT STEVEN,350000,NaN,-400729,NaN,steven.elliott@enron.com,4890344,78552,NaN,NaN,NaN,...,NaN,12961,False,1788391,NaN,170941,NaN,NaN,211725,6678735
FALLON JAMES B,2500000,NaN,NaN,NaN,jim.fallon@enron.com,940257,95924,75,42,37,...,374347,401481,False,1392142,NaN,304588,1604,1755,3676340,2332399
FASTOW ANDREW S,1300000,NaN,-1386055,NaN,andrew.fastow@enron.com,NaN,55921,NaN,NaN,NaN,...,1736055,277464,True,1794412,NaN,440698,NaN,NaN,2424083,1794412
FITZGERALD JAY L,350000,NaN,NaN,NaN,jay.fitzgerald@enron.com,664461,23870,16,1,8,...,556416,285414,False,956775,NaN,199157,723,936,1414857,1621236
FOWLER PEGGY,NaN,NaN,NaN,NaN,kulvinder.fowler@enron.com,1324578,NaN,36,0,0,...,NaN,NaN,False,560170,NaN,NaN,10,517,NaN,1884748
FOY JOE,NaN,181755,NaN,NaN,tracy.foy@enron.com,343434,NaN,13,0,0,...,NaN,NaN,False,NaN,NaN,NaN,2,57,181755,343434
FREVERT MARK A,2000000,6426990,-3367011,NaN,mark.frevert@enron.com,10433518,86987,21,242,6,...,1617011,7427621,False,4188667,NaN,1060932,2979,3275,17252530,14622185
FUGH JOHN L,NaN,50591,NaN,NaN,NaN,176378,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,50591,176378
GAHN ROBERT S,509870,73122,-1042,NaN,NaN,83237,50080,NaN,NaN,NaN,...,NaN,76547,False,235370,NaN,192008,NaN,NaN,900585,318607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MORAN MICHAEL P,NaN,NaN,NaN,NaN,michael.moran@enron.com,59539,NaN,19,0,0,...,NaN,NaN,False,161602,NaN,NaN,127,672,NaN,221141
MORDAUNT KRISTINA M,325000,NaN,NaN,NaN,kristina.mordaunt@enron.com,NaN,35018,NaN,NaN,NaN,...,NaN,1411,False,208510,NaN,267093,NaN,NaN,628522,208510
MULLER MARK S,1100000,842924,-719000,NaN,s..muller@enron.com,1056320,NaN,16,12,0,...,1725545,947,False,360528,NaN,251654,114,136,3202070,1416848
MURRAY JULIA H,400000,NaN,NaN,NaN,julia.murray@enron.com,400478,57580,45,11,2,...,125000,330,False,196983,NaN,229284,395,2192,812194,597461
NOLES JAMES L,NaN,774401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,463261,-94556,NaN,NaN,NaN,774401,368705
OLSON CINDY K,750000,77716,NaN,NaN,cindy.olson@enron.com,1637034,63791,52,20,15,...,100000,972,False,969729,NaN,329078,856,1184,1321557,2606763
OVERDYKE JR JERE C,NaN,NaN,NaN,NaN,jere.overdyke@enron.com,5266578,18834,NaN,NaN,NaN,...,135836,176,False,2041016,NaN,94941,NaN,NaN,249787,7307594
PAI LOU L,1000000,NaN,NaN,NaN,lou.pai@enron.com,15364167,32047,NaN,NaN,NaN,...,NaN,1829457,False,8453763,NaN,261879,NaN,NaN,3123383,23817930
PEREIRA PAULO V. FERRAZ,NaN,NaN,-101250,101250,NaN,NaN,27942,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,27942,NaN
PICKERING MARK R,300000,NaN,NaN,NaN,mark.pickering@enron.com,28798,31653,67,7,0,...,NaN,NaN,False,NaN,NaN,655037,728,898,1386690,28798
PIPER GREGORY F,400000,1130036,-33333,NaN,greg.piper@enron.com,880290,43057,222,61,48,...,NaN,778,False,409554,-409554,197091,742,1238,1737629,880290
PIRO JIM,NaN,NaN,NaN,NaN,jim.piro@enron.com,NaN,NaN,16,0,1,...,NaN,NaN,False,47304,NaN,NaN,3,58,NaN,47304
POWERS WILLIAM,NaN,NaN,-17500,17500,ken.powers@enron.com,NaN,NaN,26,0,0,...,NaN,NaN,False,NaN,NaN,NaN,12,653,NaN,NaN
PRENTICE JAMES,NaN,564348,NaN,NaN,james.prentice@enron.com,886231,NaN,NaN,NaN,NaN,...,NaN,NaN,False,208809,NaN,NaN,NaN,NaN,564348,1095040
REDMOND BRIAN L,NaN,NaN,NaN,NaN,brian.redmond@enron.com,7509039,14689,221,204,49,...,NaN,NaN,False,381285,NaN,96840,1063,1671,111529,7890324
REYNOLDS LAWRENCE,100000,51365,-200000,NaN,NaN,4160672,8409,NaN,NaN,NaN,...,156250,202052,False,201483,-140264,76399,NaN,NaN,394475,4221891
RICE KENNETH D,1750000,NaN,-3504386,NaN,ken.rice@enron.com,19794175,46950,18,42,4,...,1617011,174839,True,2748364,NaN,420636,864,905,505050,22542539
RIEKER PAULA H,700000,214678,-100000,NaN,paula.rieker@enron.com,1635238,33271,82,35,48,...,NaN,1950,True,283649,NaN,249201,1258,1328,1099100,1918887
SAVAGE FRANK,NaN,NaN,-121284,125034,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,3750,NaN
SCRIMSHAW MATTHEW,NaN,NaN,NaN,NaN,matthew.scrimshaw@enron.com,759557,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,759557
SHANKMAN JEFFREY A,2000000,NaN,NaN,NaN,jeffrey.shankman@enron.com,1441898,178979,2681,94,83,...,554422,1191,False,630137,NaN,304110,1730,3221,3038702,2072035
SHAPIRO RICHARD S,650000,NaN,NaN,NaN,richard.shapiro@enron.com,607837,137767,1215,74,65,...,NaN,705,False,379164,NaN,269076,4527,15149,1057548,987001
SHARP VICTORIA T,600000,187469,NaN,NaN,vicki.sharp@enron.com,281073,116337,136,24,6,...,422158,2401,False,213063,NaN,248146,2477,3136,1576511,494136
SHELBY REX,200000,NaN,-4167,NaN,rex.shelby@enron.com,1624396,22884,39,13,14,...,NaN,1573324,True,869220,NaN,211844,91,225,2003885,2493616
SHERRICK JEFFREY B,NaN,NaN,NaN,NaN,jeffrey.sherrick@enron.com,1426469,NaN,25,39,18,...,NaN,NaN,False,405999,NaN,NaN,583,613,NaN,1832468
SHERRIFF JOHN R,1500000,NaN,NaN,NaN,john.sherriff@enron.com,1835558,NaN,92,28,23,...,554422,1852186,False,1293424,NaN,428780,2103,3187,4335388,3128982
SKILLING JEFFREY K,5600000,NaN,NaN,NaN,jeff.skilling@enron.com,19250000,29336,108,88,30,...,1920000,22122,True,6843672,NaN,1111258,2042,3627,8682716,26093672
STABLER FRANK,500000,NaN,NaN,NaN,frank.stabler@enron.com,NaN,16514,NaN,NaN,NaN,...,NaN,356071,False,511734,NaN,239502,NaN,NaN,1112087,511734
SULLIVAN-SHAKLOVITZ COLLEEN,100000,181993,NaN,NaN,NaN,1362375,NaN,NaN,NaN,NaN,...,554422,162,False,NaN,NaN,162779,NaN,NaN,999356,1362375
SUNDE MARTIN,700000,NaN,NaN,NaN,marty.sunde@enron.com,NaN,NaN,38,37,13,...,476451,111122,False,698920,NaN,257486,2565,2647,1545059,698920
TAYLOR MITCHELL S,600000,227449,NaN,NaN,mitchell.taylor@enron.com,3181250,NaN,29,0,0,...,NaN,NaN,False,563798,NaN,265214,300,533,1092663,3745048
THE TRAVEL AGENCY IN THE PARK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,362096,False,NaN,NaN,NaN,NaN,NaN,362096,NaN
THORN TERENCE H,NaN,16586,NaN,NaN,terence.thorn@enron.com,4452476,46145,41,0,0,...,200000,426629,False,365320,NaN,222093,73,266,911453,4817796
TILNEY ELIZABETH A,300000,NaN,-575000,NaN,elizabeth.tilney@enron.com,591250,NaN,19,10,11,...,275000,152055,False,576792,NaN,247338,379,460,399393,1168042
TOTAL,97343619,32083396,-27992891,1398517,NaN,311764000,5235198,NaN,NaN,NaN,...,48521928,42667589,False,130322299,-7576788,26704229,NaN,NaN,309886585,434509511
UMANOFF ADAM S,788750,NaN,NaN,NaN,adam.umanoff@enron.com,NaN,53122,18,12,0,...,NaN,NaN,False,NaN,NaN,288589,41,111,1130461,NaN
URQUHART JOHN A,NaN,NaN,-36666,36666,NaN,NaN,228656,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,228656,NaN
WAKEHAM JOHN,NaN,NaN,NaN,109298,NaN,NaN,103773,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,213071,NaN
WALLS JR ROBERT H,850000,NaN,NaN,NaN,rob.walls@enron.com,4346544,50936,146,17,0,...,540751,2,False,1552453,NaN,357091,215,671,1798780,5898997
WALTERS GARETH W,NaN,53625,NaN,NaN,NaN,1030329,33785,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,87410,1030329
WASAFF GEORGE,325000,831299,-583325,NaN,george.wasaff@enron.com,1668260,NaN,30,22,7,...,200000,1425,False,388167,NaN,259996,337,400,1034395,2056427
WESTFAHL RICHARD K,NaN,NaN,-10800,NaN,dick.westfahl@enron.com,NaN,51870,NaN,NaN,NaN,...,256191,401130,False,384930,NaN,63744,NaN,NaN,762135,384930
WHALEY DAVID A,NaN,NaN,NaN,NaN,NaN,98718,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,98718
WHALLEY LAWRENCE G,3000000,NaN,NaN,NaN,greg.whalley@enron.com,3282960,57838,556,186,24,...,808346,301026,False,2796177,NaN,510364,3920,6019,4677574,6079137
WHITE JR THOMAS E,450000,NaN,NaN,NaN,thomas.white@enron.com,1297049,81353,NaN,NaN,NaN,...,NaN,1085463,False,13847074,NaN,317543,NaN,NaN,1934359,15144123
WINOKUR JR. HERBERT S,NaN,NaN,-25000,108579,NaN,NaN,1413,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,84992,NaN
WODRASKA JOHN,NaN,NaN,NaN,NaN,john.wodraska@enron.com,NaN,NaN,NaN,NaN,NaN,...,NaN,189583,False,NaN,NaN,NaN,NaN,NaN,189583,NaN
WROBEL BRUCE,NaN,NaN,NaN,NaN,NaN,139130,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,139130
YEAGER F SCOTT,NaN,NaN,NaN,NaN,scott.yeager@enron.com,8308552,53947,NaN,NaN,NaN,...,NaN,147950,True,3576206,NaN,158403,NaN,NaN,360300,11884758
YEAP SOON,NaN,NaN,NaN,NaN,NaN,192758,55097,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,55097,192758

# Exercises
Use `pandas` to answer questions regarding the Enron dataset. If you're uncertain how to do something, feel free to ask questions, look through [the `pandas` documentation](http://pandas.pydata.org/pandas-docs/stable/api.html), or refer to the code examples above!

You can check your solutions to each of these exercises by entering your answer in the corresponding Quiz in the "Datasets and Questions" lesson. I put the corresponding quizzes in parenthesis after each exercise, so you know where to go to check your answers.

Types of Data Quizzes: Questions 1-6 answer options

- numerical- numerical values (numbers)
- categorical- limited number of discrete values (category)
- time series- temporal value (date, timestamp) 
- text- words
- other

## Question 1
What type of data is salary info? (Quiz: Types of Data 1)

Number

## Question 2
What type of data is job title? (Quiz: Types of Data 2)

Categorical

## Question 3
What type of data is timestamps on emails? (Quiz: Types of Data 3)

time-series

## Question 4
What type of data is contents of emails? (Quiz: Types of Data 4)

text-words

## Question 5
What type of data is number of emails sent by a given person? (Quiz: Types of Data 5)


Number

## Question 6
What type of data is to/from fields of emails? (Quiz: Types of Data 6)


text-words

## Question 7
How many data points (people) are in the data set? (Quiz: Size of the Enron Dataset)

In [120]:
len(enron_df.index)

146

## Question 8
For each person, how many features are available? (Quiz: Features in the Enron Dataset)

In [121]:
len(enron_df.columns)

21

## Question 9
How many Persons of Interest (POIs) are in the dataset? (Quiz: Finding POIs in the Enron Data)

In [122]:
len(enron_df[enron_df['poi']])
# len(enron_df[enron_df['poi'] == False])

18

## Question 10
We compiled a list of all POI names (in `final_project/poi_names.txt`) and associated email addresses (in `final_project/poi_email_addresses.py`).

How many POI’s were there total? Use the **names** file, not the email addresses, since many folks have more than one address and a few didn’t work for Enron, so we don’t have their emails. (Quiz: How Many POIs Exist?)

**Hint:** Open up the `poi_names.txt` file to see the file format:
  - the first line is a link to a USA Today article
  - the second line is blank
  - subsequent lines have the format: `(•) Lastname, Firstname`
      - the dot `•` is either "y" (for yes) or "n" (for no), describing if the emails for that POI are available

In [123]:
poi_names = "final_project/poi_names.txt"

poi_emails = []

poi_first_name = []

poi_last_name = []

with open(poi_names, 'r') as f:
    # skip usa today url
    usa_today_url = f.readline()
    #skip the second blank line
    f.readline()

    for line in f:
        name = line.split(" ")
        print name

        poi_emails.append(name[0][1]=="y")
        poi_first_name.append(name[1][:-1])
        poi_last_name.append(name[2][:-1])


len(poi_first_name)

['(y)', 'Lay,', 'Kenneth\n']
['(y)', 'Skilling,', 'Jeffrey\n']
['(n)', 'Howard,', 'Kevin\n']
['(n)', 'Krautz,', 'Michael\n']
['(n)', 'Yeager,', 'Scott\n']
['(n)', 'Hirko,', 'Joseph\n']
['(n)', 'Shelby,', 'Rex\n']
['(n)', 'Bermingham,', 'David\n']
['(n)', 'Darby,', 'Giles\n']
['(n)', 'Mulgrew,', 'Gary\n']
['(n)', 'Bayley,', 'Daniel\n']
['(n)', 'Brown,', 'James\n']
['(n)', 'Furst,', 'Robert\n']
['(n)', 'Fuhs,', 'William\n']
['(n)', 'Causey,', 'Richard\n']
['(n)', 'Calger,', 'Christopher\n']
['(n)', 'DeSpain,', 'Timothy\n']
['(n)', 'Hannon,', 'Kevin\n']
['(n)', 'Koenig,', 'Mark\n']
['(y)', 'Forney,', 'John\n']
['(n)', 'Rice,', 'Kenneth\n']
['(n)', 'Rieker,', 'Paula\n']
['(n)', 'Fastow,', 'Lea\n']
['(n)', 'Fastow,', 'Andrew\n']
['(y)', 'Delainey,', 'David\n']
['(n)', 'Glisan,', 'Ben\n']
['(n)', 'Richter,', 'Jeffrey\n']
['(n)', 'Lawyer,', 'Larry\n']
['(n)', 'Belden,', 'Timothy\n']
['(n)', 'Kopper,', 'Michael\n']
['(n)', 'Duncan,', 'David\n']
['(n)', 'Bowen,', 'Raymond\n']
['(n)', 'Colwell,', 'Wesley\n']
['(n)', 'Boyle,', 'Dan\n']
['(n)', 'Loehr,', 'Christopher\n']

35

## Question 11
What might be a problem with having some POIs missing from our dataset? (Quiz: Problems with Incomplete Data)

Introduces bias

## Question 12
What is the total value of the stock belonging to James Prentice? (Query The Dataset 1)

In [124]:
print enron_df.columns
print enron_df.index.str.contains("Prentice", case=False)
print enron_df[enron_df.index.str.contains("Prentice", case=False)]
# For text analytics, index.str.contains is useful for text analytics
enron_df[enron_df.index.str.contains("Prentice", case=False)]['total_stock_value']

Index([u'bonus', u'deferral_payments', u'deferred_income', u'director_fees',
       u'email_address', u'exercised_stock_options', u'expenses',
       u'from_messages', u'from_poi_to_this_person',
       u'from_this_person_to_poi', u'loan_advances', u'long_term_incentive',
       u'other', u'poi', u'restricted_stock', u'restricted_stock_deferred',
       u'salary', u'shared_receipt_with_poi', u'to_messages',
       u'total_payments', u'total_stock_value'],
      dtype='object')
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]
               bonus deferral_payments deferred_income director_fees  \
PRENTICE JAMES   NaN            564348             NaN           NaN

                           email_address exercised_stock_options expenses  \
PRENTICE JAMES  james.prentice@enron.com                  886231      NaN

               from_messages from_poi_to_this_person from_this_person_to_poi  \
PRENTICE JAMES           NaN                     NaN                     NaN

                      ...        long_term_incentive other    poi  \
PRENTICE JAMES        ...                        NaN   NaN  False

               restricted_stock restricted_stock_deferred salary  \
PRENTICE JAMES           208809                       NaN    NaN

               shared_receipt_with_poi to_messages total_payments  \
PRENTICE JAMES                     NaN         NaN         564348

               total_stock_value
PRENTICE JAMES           1095040

[1 rows x 21 columns]

PRENTICE JAMES    1095040
Name: total_stock_value, dtype: object

## Question 13
How many email messages do we have from Wesley Colwell to persons of interest? (Query The Dataset 2)

In [125]:
enron_df[enron_df.index.str.contains("Colwell", case=False)]['from_this_person_to_poi']

COLWELL WESLEY    11
Name: from_this_person_to_poi, dtype: object

## Question 14
What's the value of stock options exercised by Jeffrey K Skilling? (Query The Dataset 3)

In [126]:
enron_df[enron_df.index.str.contains("Skilling", case=False)]['exercised_stock_options']

SKILLING JEFFREY K    19250000
Name: exercised_stock_options, dtype: object

**Questions 15-18 can be answered by some basic online research** 

## Question 15
Which of these schemes was Enron **not** involved in? (Quiz: Research the Enron Fraud)

- selling assets to shell companies at the end of each month, and buying them back at the beginning of the next month to hide accounting losses
- causing electrical grid failures in California
- illegally obtained a government report that enabled them to corner the market on frozen concentrated orange juice futures
- conspiring to give a Saudi prince expedited American citizenship
- a plan in collaboration with Blockbuster movies to stream movies over the internet

## Question 16
Who was the CEO of Enron during most of the time that fraud was being perpetrated? (Quiz: Enron CEO)

## Question 17
Who was chairman of the Enron board of directors? (Quiz: Enron Chairman)

## Question 18
Who was CFO (chief financial officer) of Enron during most of the time that fraud was going on? (Quiz: Enron CFO)

## Question 19
Of these three individuals (Lay, Skilling and Fastow), who took home the most money (largest value of “total_payments” feature)?(Quiz: Follow The Money)

How much money did that person get?

In [127]:
enron_df[(enron_df.index.str.contains("Lay", case=False)) | \
         (enron_df.index.str.contains("Skilling", case=False)) | \
         (enron_df.index.str.contains("Fastow", case=False))]['total_payments']

FASTOW ANDREW S         2424083
LAY KENNETH L         103559793
SKILLING JEFFREY K      8682716
Name: total_payments, dtype: object

## Question 20
For nearly every person in the dataset, not every feature has a value. How is it denoted when a feature doesn’t have a well-defined value? (Quiz: Unfilled Features)

In [128]:
enron_df

,bonus,deferral_payments,deferred_income,director_fees,email_address,exercised_stock_options,expenses,from_messages,from_poi_to_this_person,from_this_person_to_poi,...,long_term_incentive,other,poi,restricted_stock,restricted_stock_deferred,salary,shared_receipt_with_poi,to_messages,total_payments,total_stock_value
ALLEN PHILLIP K,4175000,2869717,-3081055,NaN,phillip.allen@enron.com,1729541,13868,2195,47,65,...,304805,152,False,126027,-126027,201955,1407,2902,4484442,1729541
BADUM JAMES P,NaN,178980,NaN,NaN,NaN,257817,3486,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,182466,257817
BANNANTINE JAMES M,NaN,NaN,-5104,NaN,james.bannantine@enron.com,4046157,56301,29,39,0,...,NaN,864523,False,1757552,-560222,477,465,566,916197,5243487
BAXTER JOHN C,1200000,1295738,-1386055,NaN,NaN,6680544,11200,NaN,NaN,NaN,...,1586055,2660303,False,3942714,NaN,267102,NaN,NaN,5634343,10623258
BAY FRANKLIN R,400000,260455,-201641,NaN,frank.bay@enron.com,NaN,129142,NaN,NaN,NaN,...,NaN,69,False,145796,-82782,239671,NaN,NaN,827696,63014
BAZELIDES PHILIP J,NaN,684694,NaN,NaN,NaN,1599641,NaN,NaN,NaN,NaN,...,93750,874,False,NaN,NaN,80818,NaN,NaN,860136,1599641
BECK SALLY W,700000,NaN,NaN,NaN,sally.beck@enron.com,NaN,37172,4343,144,386,...,NaN,566,False,126027,NaN,231330,2639,7315,969068,126027
BELDEN TIMOTHY N,5249999,2144013,-2334434,NaN,tim.belden@enron.com,953136,17355,484,228,108,...,NaN,210698,True,157569,NaN,213999,5521,7991,5501630,1110705
BELFER ROBERT,NaN,-102500,NaN,3285,NaN,3285,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,44093,NaN,NaN,NaN,102500,-44093
BERBERIAN DAVID,NaN,NaN,NaN,NaN,david.berberian@enron.com,1624396,11892,NaN,NaN,NaN,...,NaN,NaN,False,869220,NaN,216582,NaN,NaN,228474,2493616
BERGSIEKER RICHARD P,250000,NaN,-485813,NaN,rick.bergsieker@enron.com,NaN,59175,59,4,0,...,180250,427316,False,659249,NaN,187922,233,383,618850,659249
BHATNAGAR SANJAY,NaN,NaN,NaN,137864,sanjay.bhatnagar@enron.com,2604490,NaN,29,0,1,...,NaN,137864,False,-2604490,15456290,NaN,463,523,15456290,NaN
BIBI PHILIPPE A,1000000,NaN,NaN,NaN,philippe.bibi@enron.com,1465734,38559,40,23,8,...,369721,425688,False,378082,NaN,213625,1336,1607,2047593,1843816
BLACHMAN JEREMY M,850000,NaN,NaN,NaN,jeremy.blachman@enron.com,765313,84208,14,25,2,...,831809,272,False,189041,NaN,248546,2326,2475,2014835,954354
BLAKE JR. NORMAN P,NaN,NaN,-113784,113784,NaN,NaN,1279,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,1279,NaN
BOWEN JR RAYMOND M,1350000,NaN,-833,NaN,raymond.bowen@enron.com,NaN,65907,27,140,15,...,974293,1621,True,252055,NaN,278601,1593,1858,2669589,252055
BROWN MICHAEL,NaN,NaN,NaN,NaN,michael.brown@enron.com,NaN,49288,41,13,1,...,NaN,NaN,False,NaN,NaN,NaN,761,1486,49288,NaN
BUCHANAN HAROLD G,500000,NaN,NaN,NaN,john.buchanan@enron.com,825464,600,125,0,0,...,304805,1215,False,189041,NaN,248017,23,1088,1054637,1014505
BUTTS ROBERT H,750000,NaN,-75000,NaN,bob.butts@enron.com,NaN,9410,NaN,NaN,NaN,...,175000,150656,False,417619,NaN,261516,NaN,NaN,1271582,417619
BUY RICHARD B,900000,649584,-694862,NaN,rick.buy@enron.com,2542813,NaN,1053,156,71,...,769862,400572,False,901657,NaN,330546,2333,3523,2355702,3444470
CALGER CHRISTOPHER F,1250000,NaN,-262500,NaN,christopher.calger@enron.com,NaN,35818,144,199,25,...,375304,486,True,126027,NaN,240189,2188,2598,1639297,126027
CARTER REBECCA C,300000,NaN,-159792,NaN,rebecca.carter@enron.com,NaN,NaN,15,29,7,...,75000,540,False,307301,-307301,261809,196,312,477557,NaN
CAUSEY RICHARD A,1000000,NaN,-235000,NaN,richard.causey@enron.com,NaN,30674,49,58,12,...,350000,307895,True,2502063,NaN,415189,1585,1892,1868758,2502063
CHAN RONNIE,NaN,NaN,-98784,98784,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,32460,-32460,NaN,NaN,NaN,NaN,NaN
CHRISTODOULOU DIOMEDES,NaN,NaN,NaN,NaN,diomedes.christodoulou@enron.com,5127155,NaN,NaN,NaN,NaN,...,NaN,NaN,False,950730,NaN,NaN,NaN,NaN,NaN,6077885
CLINE KENNETH W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,662086,-472568,NaN,NaN,NaN,NaN,189518
COLWELL WESLEY,1200000,27610,-144062,NaN,wes.colwell@enron.com,NaN,16514,40,240,11,...,NaN,101740,True,698242,NaN,288542,1132,1758,1490344,698242
CORDES WILLIAM R,NaN,NaN,NaN,NaN,bill.cordes@enron.com,651850,NaN,12,10,0,...,NaN,NaN,False,386335,NaN,NaN,58,764,NaN,1038185
COX DAVID,800000,NaN,-41250,NaN,chip.cox@enron.com,117551,27861,33,0,4,...,NaN,494,False,378082,NaN,314288,71,102,1101393,495633
CUMBERLAND MICHAEL S,325000,NaN,NaN,NaN,NaN,NaN,22344,NaN,NaN,NaN,...,275000,713,False,207940,NaN,184899,NaN,NaN,807956,207940
DEFFNER JOSEPH M,600000,NaN,NaN,NaN,joseph.deffner@enron.com,17378,41626,74,115,4,...,335349,25553,False,141833,NaN,206121,552,714,1208649,159211
DELAINEY DAVID W,3000000,NaN,NaN,NaN,david.delainey@enron.com,2291113,86174,3069,66,609,...,1294981,1661,True,1323148,NaN,365163,2097,3093,4747979,3614261
DERRICK JR. JAMES V,800000,NaN,-1284000,NaN,james.derrick@enron.com,8831913,51124,909,64,20,...,484000,7482,False,1787380,-1787380,492375,1401,2181,550981,8831913
DETMERING TIMOTHY J,425000,875307,-775241,NaN,timothy.detmering@enron.com,2027865,52255,NaN,NaN,NaN,...,415657,1105,False,315068,-315068,210500,NaN,NaN,1204583,2027865
DIETRICH JANET R,600000,NaN,NaN,NaN,janet.dietrich@enron.com,1550019,3475,63,305,14,...,556416,473,False,315068,NaN,250100,1902,2572,1410464,1865087
DIMICHELE RICHARD G,1000000,NaN,NaN,NaN,richard.dimichele@enron.com,8191755,35812,NaN,NaN,NaN,...,694862,374689,False,126027,NaN,262788,NaN,NaN,2368151,8317782
DODSON KEITH,70000,NaN,NaN,NaN,keith.dodson@enron.com,NaN,28164,14,10,3,...,NaN,774,False,NaN,NaN,221003,114,176,319941,NaN
DONAHUE JR JEFFREY M,800000,NaN,-300000,NaN,jeff.donahue@enron.com,765920,96268,22,188,11,...,NaN,891,False,315068,NaN,278601,772,865,875760,1080988
DUNCAN JOHN H,NaN,NaN,-25000,102492,NaN,371750,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,77492,371750
DURAN WILLIAM D,750000,NaN,NaN,NaN,w.duran@enron.com,1451869,25785,12,106,3,...,1105218,1568,False,189041,NaN,210692,599,904,2093263,1640910
ECHOLS JOHN B,200000,NaN,NaN,NaN,john.echols@enron.com,601438,21530,NaN,NaN,NaN,...,2234774,53775,False,407503,NaN,182245,NaN,NaN,2692324,1008941
ELLIOTT STEVEN,350000,NaN,-400729,NaN,steven.elliott@enron.com,4890344,78552,NaN,NaN,NaN,...,NaN,12961,False,1788391,NaN,170941,NaN,NaN,211725,6678735
FALLON JAMES B,2500000,NaN,NaN,NaN,jim.fallon@enron.com,940257,95924,75,42,37,...,374347,401481,False,1392142,NaN,304588,1604,1755,3676340,2332399
FASTOW ANDREW S,1300000,NaN,-1386055,NaN,andrew.fastow@enron.com,NaN,55921,NaN,NaN,NaN,...,1736055,277464,True,1794412,NaN,440698,NaN,NaN,2424083,1794412
FITZGERALD JAY L,350000,NaN,NaN,NaN,jay.fitzgerald@enron.com,664461,23870,16,1,8,...,556416,285414,False,956775,NaN,199157,723,936,1414857,1621236
FOWLER PEGGY,NaN,NaN,NaN,NaN,kulvinder.fowler@enron.com,1324578,NaN,36,0,0,...,NaN,NaN,False,560170,NaN,NaN,10,517,NaN,1884748
FOY JOE,NaN,181755,NaN,NaN,tracy.foy@enron.com,343434,NaN,13,0,0,...,NaN,NaN,False,NaN,NaN,NaN,2,57,181755,343434
FREVERT MARK A,2000000,6426990,-3367011,NaN,mark.frevert@enron.com,10433518,86987,21,242,6,...,1617011,7427621,False,4188667,NaN,1060932,2979,3275,17252530,14622185
FUGH JOHN L,NaN,50591,NaN,NaN,NaN,176378,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,50591,176378
GAHN ROBERT S,509870,73122,-1042,NaN,NaN,83237,50080,NaN,NaN,NaN,...,NaN,76547,False,235370,NaN,192008,NaN,NaN,900585,318607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MORAN MICHAEL P,NaN,NaN,NaN,NaN,michael.moran@enron.com,59539,NaN,19,0,0,...,NaN,NaN,False,161602,NaN,NaN,127,672,NaN,221141
MORDAUNT KRISTINA M,325000,NaN,NaN,NaN,kristina.mordaunt@enron.com,NaN,35018,NaN,NaN,NaN,...,NaN,1411,False,208510,NaN,267093,NaN,NaN,628522,208510
MULLER MARK S,1100000,842924,-719000,NaN,s..muller@enron.com,1056320,NaN,16,12,0,...,1725545,947,False,360528,NaN,251654,114,136,3202070,1416848
MURRAY JULIA H,400000,NaN,NaN,NaN,julia.murray@enron.com,400478,57580,45,11,2,...,125000,330,False,196983,NaN,229284,395,2192,812194,597461
NOLES JAMES L,NaN,774401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,463261,-94556,NaN,NaN,NaN,774401,368705
OLSON CINDY K,750000,77716,NaN,NaN,cindy.olson@enron.com,1637034,63791,52,20,15,...,100000,972,False,969729,NaN,329078,856,1184,1321557,2606763
OVERDYKE JR JERE C,NaN,NaN,NaN,NaN,jere.overdyke@enron.com,5266578,18834,NaN,NaN,NaN,...,135836,176,False,2041016,NaN,94941,NaN,NaN,249787,7307594
PAI LOU L,1000000,NaN,NaN,NaN,lou.pai@enron.com,15364167,32047,NaN,NaN,NaN,...,NaN,1829457,False,8453763,NaN,261879,NaN,NaN,3123383,23817930
PEREIRA PAULO V. FERRAZ,NaN,NaN,-101250,101250,NaN,NaN,27942,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,27942,NaN
PICKERING MARK R,300000,NaN,NaN,NaN,mark.pickering@enron.com,28798,31653,67,7,0,...,NaN,NaN,False,NaN,NaN,655037,728,898,1386690,28798
PIPER GREGORY F,400000,1130036,-33333,NaN,greg.piper@enron.com,880290,43057,222,61,48,...,NaN,778,False,409554,-409554,197091,742,1238,1737629,880290
PIRO JIM,NaN,NaN,NaN,NaN,jim.piro@enron.com,NaN,NaN,16,0,1,...,NaN,NaN,False,47304,NaN,NaN,3,58,NaN,47304
POWERS WILLIAM,NaN,NaN,-17500,17500,ken.powers@enron.com,NaN,NaN,26,0,0,...,NaN,NaN,False,NaN,NaN,NaN,12,653,NaN,NaN
PRENTICE JAMES,NaN,564348,NaN,NaN,james.prentice@enron.com,886231,NaN,NaN,NaN,NaN,...,NaN,NaN,False,208809,NaN,NaN,NaN,NaN,564348,1095040
REDMOND BRIAN L,NaN,NaN,NaN,NaN,brian.redmond@enron.com,7509039,14689,221,204,49,...,NaN,NaN,False,381285,NaN,96840,1063,1671,111529,7890324
REYNOLDS LAWRENCE,100000,51365,-200000,NaN,NaN,4160672,8409,NaN,NaN,NaN,...,156250,202052,False,201483,-140264,76399,NaN,NaN,394475,4221891
RICE KENNETH D,1750000,NaN,-3504386,NaN,ken.rice@enron.com,19794175,46950,18,42,4,...,1617011,174839,True,2748364,NaN,420636,864,905,505050,22542539
RIEKER PAULA H,700000,214678,-100000,NaN,paula.rieker@enron.com,1635238,33271,82,35,48,...,NaN,1950,True,283649,NaN,249201,1258,1328,1099100,1918887
SAVAGE FRANK,NaN,NaN,-121284,125034,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,3750,NaN
SCRIMSHAW MATTHEW,NaN,NaN,NaN,NaN,matthew.scrimshaw@enron.com,759557,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,759557
SHANKMAN JEFFREY A,2000000,NaN,NaN,NaN,jeffrey.shankman@enron.com,1441898,178979,2681,94,83,...,554422,1191,False,630137,NaN,304110,1730,3221,3038702,2072035
SHAPIRO RICHARD S,650000,NaN,NaN,NaN,richard.shapiro@enron.com,607837,137767,1215,74,65,...,NaN,705,False,379164,NaN,269076,4527,15149,1057548,987001
SHARP VICTORIA T,600000,187469,NaN,NaN,vicki.sharp@enron.com,281073,116337,136,24,6,...,422158,2401,False,213063,NaN,248146,2477,3136,1576511,494136
SHELBY REX,200000,NaN,-4167,NaN,rex.shelby@enron.com,1624396,22884,39,13,14,...,NaN,1573324,True,869220,NaN,211844,91,225,2003885,2493616
SHERRICK JEFFREY B,NaN,NaN,NaN,NaN,jeffrey.sherrick@enron.com,1426469,NaN,25,39,18,...,NaN,NaN,False,405999,NaN,NaN,583,613,NaN,1832468
SHERRIFF JOHN R,1500000,NaN,NaN,NaN,john.sherriff@enron.com,1835558,NaN,92,28,23,...,554422,1852186,False,1293424,NaN,428780,2103,3187,4335388,3128982
SKILLING JEFFREY K,5600000,NaN,NaN,NaN,jeff.skilling@enron.com,19250000,29336,108,88,30,...,1920000,22122,True,6843672,NaN,1111258,2042,3627,8682716,26093672
STABLER FRANK,500000,NaN,NaN,NaN,frank.stabler@enron.com,NaN,16514,NaN,NaN,NaN,...,NaN,356071,False,511734,NaN,239502,NaN,NaN,1112087,511734
SULLIVAN-SHAKLOVITZ COLLEEN,100000,181993,NaN,NaN,NaN,1362375,NaN,NaN,NaN,NaN,...,554422,162,False,NaN,NaN,162779,NaN,NaN,999356,1362375
SUNDE MARTIN,700000,NaN,NaN,NaN,marty.sunde@enron.com,NaN,NaN,38,37,13,...,476451,111122,False,698920,NaN,257486,2565,2647,1545059,698920
TAYLOR MITCHELL S,600000,227449,NaN,NaN,mitchell.taylor@enron.com,3181250,NaN,29,0,0,...,NaN,NaN,False,563798,NaN,265214,300,533,1092663,3745048
THE TRAVEL AGENCY IN THE PARK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,362096,False,NaN,NaN,NaN,NaN,NaN,362096,NaN
THORN TERENCE H,NaN,16586,NaN,NaN,terence.thorn@enron.com,4452476,46145,41,0,0,...,200000,426629,False,365320,NaN,222093,73,266,911453,4817796
TILNEY ELIZABETH A,300000,NaN,-575000,NaN,elizabeth.tilney@enron.com,591250,NaN,19,10,11,...,275000,152055,False,576792,NaN,247338,379,460,399393,1168042
TOTAL,97343619,32083396,-27992891,1398517,NaN,311764000,5235198,NaN,NaN,NaN,...,48521928,42667589,False,130322299,-7576788,26704229,NaN,NaN,309886585,434509511
UMANOFF ADAM S,788750,NaN,NaN,NaN,adam.umanoff@enron.com,NaN,53122,18,12,0,...,NaN,NaN,False,NaN,NaN,288589,41,111,1130461,NaN
URQUHART JOHN A,NaN,NaN,-36666,36666,NaN,NaN,228656,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,228656,NaN
WAKEHAM JOHN,NaN,NaN,NaN,109298,NaN,NaN,103773,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,213071,NaN
WALLS JR ROBERT H,850000,NaN,NaN,NaN,rob.walls@enron.com,4346544,50936,146,17,0,...,540751,2,False,1552453,NaN,357091,215,671,1798780,5898997
WALTERS GARETH W,NaN,53625,NaN,NaN,NaN,1030329,33785,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,87410,1030329
WASAFF GEORGE,325000,831299,-583325,NaN,george.wasaff@enron.com,1668260,NaN,30,22,7,...,200000,1425,False,388167,NaN,259996,337,400,1034395,2056427
WESTFAHL RICHARD K,NaN,NaN,-10800,NaN,dick.westfahl@enron.com,NaN,51870,NaN,NaN,NaN,...,256191,401130,False,384930,NaN,63744,NaN,NaN,762135,384930
WHALEY DAVID A,NaN,NaN,NaN,NaN,NaN,98718,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,98718
WHALLEY LAWRENCE G,3000000,NaN,NaN,NaN,greg.whalley@enron.com,3282960,57838,556,186,24,...,808346,301026,False,2796177,NaN,510364,3920,6019,4677574,6079137
WHITE JR THOMAS E,450000,NaN,NaN,NaN,thomas.white@enron.com,1297049,81353,NaN,NaN,NaN,...,NaN,1085463,False,13847074,NaN,317543,NaN,NaN,1934359,15144123
WINOKUR JR. HERBERT S,NaN,NaN,-25000,108579,NaN,NaN,1413,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,84992,NaN
WODRASKA JOHN,NaN,NaN,NaN,NaN,john.wodraska@enron.com,NaN,NaN,NaN,NaN,NaN,...,NaN,189583,False,NaN,NaN,NaN,NaN,NaN,189583,NaN
WROBEL BRUCE,NaN,NaN,NaN,NaN,NaN,139130,NaN,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,139130
YEAGER F SCOTT,NaN,NaN,NaN,NaN,scott.yeager@enron.com,8308552,53947,NaN,NaN,NaN,...,NaN,147950,True,3576206,NaN,158403,NaN,NaN,360300,11884758
YEAP SOON,NaN,NaN,NaN,NaN,NaN,192758,55097,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,55097,192758

## Question 21
How many folks in this dataset have a quantified salary? What about a known email address? (Quiz: Dealing with Unfilled Features)

In [129]:
# you cannot leave the == sign blank because the values are not boolean values
len(enron_df[enron_df['salary'] != 'NaN'])

95

## More Magic Functions

In the Jupyter Notebook `lesson 1`, we introduced our first [Magic Function](http://ipython.readthedocs.io/en/stable/interactive/tutorial.html#magics-explained):

`%matplotlib inline`

That allowed us to generate plots using `matplotlib.pyplot` that appeared directly within our Jupyter Notebook! Earlier in this notebook, we also introduced the Magic Function:

`%cd "..."`

Replacing the ellipses in the above Magic Function with the path of the **ud120-projects** repo allowed us to change the working directory for this Jupyter Notebook session. Let's learn one last Magic Function:

`%load filename.py`

This allows us to quickly load python code from the file `filename.py` into the current cell.

**Run** the cell below to execute the Magic Function `%load tools/feature_format.py` from the **ud120-projects** repo. What happens?

In [130]:
# %load tools/feature_format.py
#!/usr/bin/python

""" 
    A general tool for converting data from the
    dictionary format to an (n x k) python list that's 
    ready for training an sklearn algorithm

    n--no. of key-value pairs in dictonary
    k--no. of features being extracted

    dictionary keys are names of persons in dataset
    dictionary values are dictionaries, where each
        key-value pair in the dict is the name
        of a feature, and its value for that person

    In addition to converting a dictionary to a numpy 
    array, you may want to separate the labels from the
    features--this is what targetFeatureSplit is for

    so, if you want to have the poi label as the target,
    and the features you want to use are the person's
    salary and bonus, here's what you would do:

    feature_list = ["poi", "salary", "bonus"] 
    data_array = featureFormat( data_dictionary, feature_list )
    label, features = targetFeatureSplit(data_array)

    the line above (targetFeatureSplit) assumes that the
    label is the _first_ item in feature_list--very important
    that poi is listed first!
"""


import numpy as np

def featureFormat( dictionary, features, remove_NaN=True, remove_all_zeroes=True, remove_any_zeroes=False, sort_keys = False):
    """ convert dictionary to numpy array of features
        remove_NaN = True will convert "NaN" string to 0.0
        remove_all_zeroes = True will omit any data points for which
            all the features you seek are 0.0
        remove_any_zeroes = True will omit any data points for which
            any of the features you seek are 0.0
        sort_keys = True sorts keys by alphabetical order. Setting the value as
            a string opens the corresponding pickle file with a preset key
            order (this is used for Python 3 compatibility, and sort_keys
            should be left as False for the course mini-projects).
        NOTE: first feature is assumed to be 'poi' and is not checked for
            removal for zero or missing values.
    """


    return_list = []

    # Key order - first branch is for Python 3 compatibility on mini-projects,
    # second branch is for compatibility on final project.
    if isinstance(sort_keys, str):
        import pickle
        keys = pickle.load(open(sort_keys, "rb"))
    elif sort_keys:
        keys = sorted(dictionary.keys())
    else:
        keys = dictionary.keys()

    for key in keys:
        tmp_list = []
        for feature in features:
            try:
                dictionary[key][feature]
            except KeyError:
                print "error: key ", feature, " not present"
                return
            value = dictionary[key][feature]
            if value=="NaN" and remove_NaN:
                value = 0
            tmp_list.append( float(value) )

        # Logic for deciding whether or not to add the data point.
        append = True
        # exclude 'poi' class as criteria.
        if features[0] == 'poi':
            test_list = tmp_list[1:]
        else:
            test_list = tmp_list
        ### if all features are zero and you want to remove
        ### data points that are all zero, do that here
        if remove_all_zeroes:
            append = False
            for item in test_list:
                if item != 0 and item != "NaN":
                    append = True
                    break
        ### if any features for a given data point are zero
        ### and you want to remove data points with any zeroes,
        ### handle that here
        if remove_any_zeroes:
            if 0 in test_list or "NaN" in test_list:
                append = False
        ### Append the data point if flagged for addition.
        if append:
            return_list.append( np.array(tmp_list) )

    return np.array(return_list)


def targetFeatureSplit( data ):
    """ 
        given a numpy array like the one returned from
        featureFormat, separate out the first feature
        and put it into its own list (this should be the 
        quantity you want to predict)

        return targets and features as separate lists

        (sklearn can generally handle both lists and numpy arrays as 
        input formats when training/predicting)
    """

    target = []
    features = []
    for item in data:
        target.append( item[0] )
        features.append( item[1:] )

    return target, features

You should see that the Magic Function `%load tools/feature_format.py` copies the contents of `feature_format.py` into the same cell, below the magic command. Additionally, the Magic Function `%load tools/feature_format.py` is now commented out. Note that you've **copied** the contents of `feature_format.py` into the cell with the Magic Function, but you need to run the cell a second time to actually **execute** the code.

If you want to try another `%load` Magic Function, **run** the cell below to load the contents of `poi_email_addresses.py` to this Notebook.

In [131]:
# %load final_project/poi_email_addresses.py
def poiEmails():
    email_list = ["kenneth_lay@enron.net",    
            "kenneth_lay@enron.com",
            "klay.enron@enron.com",
            "kenneth.lay@enron.com", 
            "klay@enron.com",
            "layk@enron.com",
            "chairman.ken@enron.com",
            "jeffreyskilling@yahoo.com",
            "jeff_skilling@enron.com",
            "jskilling@enron.com",
            "effrey.skilling@enron.com",
            "skilling@enron.com",
            "jeffrey.k.skilling@enron.com",
            "jeff.skilling@enron.com",
            "kevin_a_howard.enronxgate.enron@enron.net",
            "kevin.howard@enron.com",
            "kevin.howard@enron.net",
            "kevin.howard@gcm.com",
            "michael.krautz@enron.com"
            "scott.yeager@enron.com",
            "syeager@fyi-net.com",
            "scott_yeager@enron.net",
            "syeager@flash.net",
            "joe'.'hirko@enron.com", 
            "joe.hirko@enron.com", 
            "rex.shelby@enron.com", 
            "rex.shelby@enron.nt", 
            "rex_shelby@enron.net",
            "jbrown@enron.com",
            "james.brown@enron.com", 
            "rick.causey@enron.com", 
            "richard.causey@enron.com", 
            "rcausey@enron.com",
            "calger@enron.com",
            "chris.calger@enron.com", 
            "christopher.calger@enron.com", 
            "ccalger@enron.com",
            "tim_despain.enronxgate.enron@enron.net", 
            "tim.despain@enron.com",
            "kevin_hannon@enron.com", 
            "kevin'.'hannon@enron.com", 
            "kevin_hannon@enron.net", 
            "kevin.hannon@enron.com",
            "mkoenig@enron.com", 
            "mark.koenig@enron.com",
            "m..forney@enron.com",
            "ken'.'rice@enron.com", 
            "ken.rice@enron.com",
            "ken_rice@enron.com", 
            "ken_rice@enron.net",
            "paula.rieker@enron.com",
            "prieker@enron.com", 
            "andrew.fastow@enron.com", 
            "lfastow@pdq.net", 
            "andrew.s.fastow@enron.com", 
            "lfastow@pop.pdq.net", 
            "andy.fastow@enron.com",
            "david.w.delainey@enron.com", 
            "delainey.dave@enron.com", 
            "'delainey@enron.com", 
            "david.delainey@enron.com", 
            "'david.delainey'@enron.com", 
            "dave.delainey@enron.com", 
            "delainey'.'david@enron.com",
            "ben.glisan@enron.com", 
            "bglisan@enron.com", 
            "ben_f_glisan@enron.com", 
            "ben'.'glisan@enron.com",
            "jeff.richter@enron.com", 
            "jrichter@nwlink.com",
            "lawrencelawyer@aol.com", 
            "lawyer'.'larry@enron.com", 
            "larry_lawyer@enron.com", 
            "llawyer@enron.com", 
            "larry.lawyer@enron.com", 
            "lawrence.lawyer@enron.com",
            "tbelden@enron.com", 
            "tim.belden@enron.com", 
            "tim_belden@pgn.com", 
            "tbelden@ect.enron.com",
            "michael.kopper@enron.com",
            "dave.duncan@enron.com", 
            "dave.duncan@cipco.org", 
            "duncan.dave@enron.com",
            "ray.bowen@enron.com", 
            "raymond.bowen@enron.com", 
            "'bowen@enron.com",
            "wes.colwell@enron.com",
            "dan.boyle@enron.com",
            "cloehr@enron.com", 
            "chris.loehr@enron.com"
        ]
    return email_list

A couple last helpful hints about Magic Functions:
  - You can learn more about Magic Functions at any time with the Magic Function `%magic`
  - You can get the list of available Magic Functions by the Magic Function `%lsmagic`
  - You can learn about any Magic Function by typing a question mark after it, *e.g.* `%load?`
  
**Try it below!**

In [132]:
%magic

# Optional Exercises -- Missing POIs
As you saw a little while ago, not every POI has an entry in the dataset (e.g. Michael Krautz). That’s because the dataset was created using the financial data you can find in `../final_project/enron61702insiderpay.pdf`, which is missing some POI’s (those absences propagated through to the final dataset). On the other hand, for many of these “missing” POI’s, we do have emails.

While it would be straightforward to add these POI’s and their email information to the E+F dataset, and just put “NaN” for their financial information, this could introduce a subtle problem. You will walk through that here.

Again, you can check your solutions to each of these exercises by entering your answer in the corresponding Quiz in the "Datasets and Questions" lesson. I put the corresponding quizzes in parenthesis after each exercise, so you know where to go to check your answers.

## Question 1
How many people in the E+F dataset (as it currently exists) have “NaN” for their total payments? What percentage of people in the dataset as a whole is this? (Quiz: Missing POIs 1 (Optional))

In [133]:
enron_df.columns

Index([u'bonus', u'deferral_payments', u'deferred_income', u'director_fees',
       u'email_address', u'exercised_stock_options', u'expenses',
       u'from_messages', u'from_poi_to_this_person',
       u'from_this_person_to_poi', u'loan_advances', u'long_term_incentive',
       u'other', u'poi', u'restricted_stock', u'restricted_stock_deferred',
       u'salary', u'shared_receipt_with_poi', u'to_messages',
       u'total_payments', u'total_stock_value'],
      dtype='object')

In [134]:
len(enron_df[enron_df['total_payments'] == "NaN"])

21

In [135]:
len(enron_df['total_payments'])

146

In [136]:
(21.0/146.0)*100.0

14.383561643835616

## Question 2
How many POIs in the E+F dataset have “NaN” for their total payments? What percentage of POI’s as a whole is this? (Quiz: Missing POIs 2 (Optional))

In [137]:
enron_df[(enron_df['poi'] == True) & (enron_df['total_payments'] == "NaN")]

Empty DataFrame
Columns: [bonus, deferral_payments, deferred_income, director_fees, email_address, exercised_stock_options, expenses, from_messages, from_poi_to_this_person, from_this_person_to_poi, loan_advances, long_term_incentive, other, poi, restricted_stock, restricted_stock_deferred, salary, shared_receipt_with_poi, to_messages, total_payments, total_stock_value]
Index: []

[0 rows x 21 columns]

## Question 3

If a machine learning algorithm were to use total_payments as a feature, would you expect it to associate a “NaN” value with POIs or non-POIs? (Quiz: Missing POIs 3 (Optional))

Non-POIs

## Question 4

If you added in, say, 10 more data points which were all POI’s, and put “NaN” for the total payments for those folks, the numbers you just calculated would change.

What is the new number of people of the dataset? What is the new number of folks with “NaN” for total payments? (Quiz: Missing POIs 4 (Optional))

In [138]:
len(enron_df) + 10

156

In [139]:
len(enron_df[enron_df['total_payments'] == "NaN"]) +10

31

## Question 5

What is the new number of POI’s in the dataset? What is the new number of POI’s with NaN for total_payments? (Quiz: Missing POIs 5 (Optional))

In [140]:
enron_df[(enron_df['poi'] == True) & (enron_df['total_payments'] == "NaN")]
# enron_df['poi'][enron_df['total_payments'] == "NaN"]

Empty DataFrame
Columns: [bonus, deferral_payments, deferred_income, director_fees, email_address, exercised_stock_options, expenses, from_messages, from_poi_to_this_person, from_this_person_to_poi, loan_advances, long_term_incentive, other, poi, restricted_stock, restricted_stock_deferred, salary, shared_receipt_with_poi, to_messages, total_payments, total_stock_value]
Index: []

[0 rows x 21 columns]

In [141]:
enron_df.shape

(146, 21)

## Question 6

Once the new data points are added, do you think a supervised classification algorithm might interpret “NaN” for total_payments as a clue that someone is a POI? (Quiz: Missing POIs 6 (Optional))